import type { PipelineSchema } from "@/Schema";
import type { StageConfig } from "@/types/Pipeline";

/**
 * Convert a canvas `PipelineSchema` into a standalone MongoDB shell script —
 * something the user can paste directly into `mongosh` or the Atlas data
 * explorer. We pick the SOURCE stage's collection as the entry point and
 * walk the remaining stages in topological order, emitting each one's
 * `operation.body` (or the implicit equivalent for stage types that don't
 * carry a free-form body) as a pipeline element.
 *
 * Branching pipelines (multiple downstreams from one stage) aren't natively
 * representable in a single `aggregate()` call — Mongo expresses branches
 * via `$facet`. For those we fall through to the linear chain that includes
 * the longest single path, and add a comment header noting which branches
 * were dropped. Hackathon-scope decision; a full $facet emitter is a
 * follow-up.
 */
export function stagesToMqlScript(schema: PipelineSchema): string {
  const stages = schema.stages ?? [];
  if (stages.length === 0) {
    return "// Empty canvas — add stages and try Export again.\n";
  }

  const source = stages.find((s) => s.type === "MQL_SOURCE");
  if (!source) {
    return "// No MQL_SOURCE stage on the canvas — can't emit a runnable script.\n";
  }

  const sourceOp = source.operation as
    | { stageType: "MQL_SOURCE"; database?: string; collection?: string }
    | undefined;
  const database = sourceOp?.database ?? "sample_mflix";
  const collection = sourceOp?.collection ?? source.output ?? "movies";

  // Walk downstream from the source along a single path. If we hit a
  // branching point, follow the first child by stage-array order (matches
  // the canvas layout's "primary branch" rule).
  const childrenById = new Map<string, string[]>();
  for (const s of stages) childrenById.set(s.id, []);
  for (const s of stages) {
    for (const dep of s.depends_on ?? []) {
      childrenById.get(dep)?.push(s.id);
    }
  }
  const stageById = new Map(stages.map((s) => [s.id, s]));

  const pathIds: string[] = [];
  let cursor: string | undefined = source.id;
  const seen = new Set<string>();
  while (cursor && !seen.has(cursor)) {
    pathIds.push(cursor);
    seen.add(cursor);
    const kids: string[] = (childrenById.get(cursor) ?? []).slice();
    // Stable order: pick the lowest array-index child.
    kids.sort(
      (a: string, b: string) =>
        stages.findIndex((s) => s.id === a) -
        stages.findIndex((s) => s.id === b),
    );
    cursor = kids[0];
  }

  const droppedBranches = stages.filter(
    (s) => !seen.has(s.id) && s.id !== source.id,
  );

  const pipelineParts: string[] = [];
  for (let i = 1; i < pathIds.length; i++) {
    const stage = stageById.get(pathIds[i]);
    if (!stage) continue;
    const fragment = operationToPipelineStage(stage.type, stage.operation);
    if (fragment) pipelineParts.push("  " + fragment);
  }

  const header = [
    `// Generated by AtlasOrbit — ${new Date().toISOString()}`,
    `// Pipeline: ${schema.pipeline?.name ?? "unnamed"}`,
    droppedBranches.length > 0
      ? `// NOTE: This pipeline has ${droppedBranches.length} branch stage(s) that aren't included in the\n// single-path export — \`aggregate\` expresses branches via \`$facet\`. Dropped:\n//   ${droppedBranches.map((s) => `${s.id} (${s.type})`).join(", ")}`
      : "",
  ]
    .filter(Boolean)
    .join("\n");

  return `${header}
use("${database}");

db.${collection}.aggregate([
${pipelineParts.join(",\n")}
]);
`;
}

function operationToPipelineStage(
  type: string,
  operation: StageConfig | unknown,
): string | null {
  if (!operation || typeof operation !== "object") return null;
  const op = operation as Record<string, unknown> & {
    stageType?: string;
    body?: unknown;
  };
  // Most MongoDB-style stages on this canvas carry the raw operator
  // object as `operation.body`. When that's present we emit `{ $stage: body }`.
  if (op.body != null) {
    const key = canonicalStageKey(type);
    if (!key) return null;
    return `{ "${key}": ${JSON.stringify(op.body, null, 2).split("\n").join("\n  ")} }`;
  }
  // Fallback for stage types where the agent uses a flatter shape (no `body`
  // wrapper). MQL_SOURCE is the only one we expect here, but we already
  // skipped it during walking; treat anything else as best-effort.
  return null;
}

function canonicalStageKey(type: string): string | null {
  switch (type) {
    case "MQL_MATCH":
    case "MQL_VECTOR_SEARCH":
      // The canvas renders vector-search nodes as purple, but the executed
      // query is plain $match + $text (see system instruction).
      return "$match";
    case "MQL_PROJECT":
      return "$project";
    case "MQL_SORT":
      return "$sort";
    case "MQL_LIMIT":
      return "$limit";
    case "MQL_GROUP":
      return "$group";
    case "MQL_LOOKUP":
      return "$lookup";
    case "MQL_UNWIND":
      return "$unwind";
    default:
      return null;
  }
}

/** Trigger a browser download of the given MQL script. */
export function downloadMqlScript(filename: string, body: string): void {
  const blob = new Blob([body], { type: "text/javascript" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".mongodb.js")
    ? filename
    : `${filename}.mongodb.js`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
