import type { PipelineSchema } from "@/Schema";

/**
 * Persist the canvas as a URL fragment so users can share a pipeline by
 * copy-pasting the page URL. The fragment never reaches the server (it's
 * client-only by spec), so this works without any backend changes and
 * doesn't leak through GCP / proxy / Cloud Run logs.
 *
 * Encoding:
 *   #s1=<base64url(JSON.stringify(schema))>
 *
 * The `s1=` prefix lets us version the format if we ever add gzip or a
 * different shape; on read we accept any unknown prefix as a soft no-op
 * rather than crashing. Empty / missing hash = no preload.
 *
 * Results rows are NOT included — they're ephemeral (regenerated by
 * re-running the agent) and would inflate the URL well past comfortable
 * sharing limits.
 */

const FRAGMENT_PREFIX = "s1=";

export function encodeSchemaToFragment(schema: PipelineSchema): string {
  const json = JSON.stringify(stripLayoutForShare(schema));
  const utf8 = new TextEncoder().encode(json);
  // Convert bytes → base64 → URL-safe (-, _) with no `=` padding so the
  // hash survives untouched through chat clients and browser address bars.
  let binary = "";
  for (const byte of utf8) binary += String.fromCharCode(byte);
  const b64 = btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
  return `#${FRAGMENT_PREFIX}${b64}`;
}

export function decodeSchemaFromFragment(
  fragment: string,
): PipelineSchema | null {
  if (!fragment) return null;
  const raw = fragment.startsWith("#") ? fragment.slice(1) : fragment;
  if (!raw.startsWith(FRAGMENT_PREFIX)) return null;
  const b64url = raw.slice(FRAGMENT_PREFIX.length);
  if (!b64url) return null;
  try {
    const b64 = b64url
      .replace(/-/g, "+")
      .replace(/_/g, "/")
      .padEnd(b64url.length + ((4 - (b64url.length % 4)) % 4), "=");
    const binary = atob(b64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    const json = new TextDecoder().decode(bytes);
    const parsed = JSON.parse(json);
    if (!parsed || typeof parsed !== "object") return null;
    return parsed as PipelineSchema;
  } catch {
    return null;
  }
}

/**
 * Drop UI-only positioning data before encoding. The receiver re-computes
 * positions via the branching DAG layout, so shipping them is wasted
 * bytes and forces the recipient into the sender's exact x/y choices.
 */
function stripLayoutForShare(schema: PipelineSchema): PipelineSchema {
  return {
    ...schema,
    layout: {
      nodes: [],
      edges: schema.layout?.edges ?? [],
    },
  };
}
